# Generated by Django 3.1.7 on 2021-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='alternativa',
            new_name='alternativas',
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa_correta',
            field=models.IntegerField(choices=[(2, 'C'), (3, 'D'), (1, 'B'), (0, 'A')]),
        ),
    ]
